### ISSUE TITLE
Can not modify the pbc of the mutable data

### ISSUE THREAD

**Issue by superstar54** [aiidateam/aiida-atomistic#28]
In the user guide:

> It is also possible to directly access the single properties and modify them, but we strongly suggest to use the dedicated `set_*`methods or the `add_atom`, `pop_atom`, `update_site`. `pbc` and `cell` can be modified only via the corresponding `set_pbc` and `set_cell` methods.

But when I try to modify the pbc, it raise an error.
```python
mutable_structure.pbc[0]=False

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_498474/36765969.py in <cell line: 0>()
----> 1 mutable_structure.pbc[0]=False

ValueError: assignment destination is read-only
```

**Comment by mikibonacci** [comment]
Yes I now, for now I just let the user set it using `set_pbc`. I am trying to make it immutable for `StructureData` but is not easy as the single element can still be changed without trigger any pbc.setter. I was trying to use the `ObservedArray` type as for the site properties but seems not working. 
Let's see if I can fix it easily
