### ISSUE TITLE
Use list of symbols when defining alloy

### ISSUE THREAD

**Issue by superstar54** [aiidateam/aiida-atomistic#42]
suggestion:
```diff
-'sites': [{'symbol': 'CuAl',
+'sites': [{'symbols': ['Cu', 'Al'],
   'position': [0.0, 0.0, 0.0],
   'weights': (0.5,0.5)
   }],})
```

**Comment by mikibonacci** [comment]
Moreover, we should think if we want to provide `symbols` list as list of lists, or we also accept hybrid list[list,str].

`symbols: [["Si"],["Si"],...]` and then we make this flat for query?

**Comment by mikibonacci** [comment]
I think that we should allow the hybrid version, where the alloy is defined not by a string but by a list of strings. This seems more intuitive. Moreover, for the user it would be more tedious to provide symbols as list of lists if we don't have alloys. 

We store the symbols only using strings, even if the user can provide a list of strings for each site. We should just make it very clear. This will be useful also for query (we don't need to query lists of lists) and in the end we can always put a property `alloy_list` which return the list. NB: not a true `StructureData` property, but a python one. (@property...)
